import { Exercise } from '../types';

export const EXERCISES: Exercise[] = [
  {
    id: 'dips',
    name: 'Dips',
    description: 'Stütze dich an der Dips-Station ab, senke den Körper kontrolliert ab und drücke dich explosiv nach oben.',
    muscleGroups: ['Brust', 'Trizeps', 'Schultern'],
    difficulty: 'Mittel',
    equipment: 'Dips-Station',
    icon: '💪',
    tips: 'Ellenbogen ca. 45° vom Körper, nicht zu tief gehen',
  },
  {
    id: 'kb-ohp',
    name: 'KB Overhead Press',
    description: 'Drücke die Kettlebell von der Schulter über den Kopf. Wechsle die Seite nach jeder Runde.',
    muscleGroups: ['Schultern', 'Trizeps'],
    difficulty: 'Mittel',
    equipment: 'Kettlebell',
    icon: '🔔',
    tips: 'Core anspannen, nicht ins Hohlkreuz fallen',
  },
  {
    id: 'push-ups-close',
    name: 'Liegestütze (eng)',
    description: 'Enge Liegestütze mit Händen unter den Schultern. Ellenbogen nah am Körper halten.',
    muscleGroups: ['Brust', 'Trizeps'],
    difficulty: 'Anfänger',
    icon: '🫸',
    tips: 'Ellenbogen eng am Körper, Brust berührt fast den Boden',
  },
  {
    id: 'pike-push-ups',
    name: 'Pike Push-ups',
    description: 'Hüfte hoch in V-Position, Kopf Richtung Boden senken. Trainiert die Schultern intensiv.',
    muscleGroups: ['Schultern', 'Trizeps'],
    difficulty: 'Mittel',
    icon: '🔻',
    tips: 'Je steiler die V-Position, desto schwerer',
  },
  {
    id: 'russian-twists',
    name: 'Russian Twists (KB)',
    description: 'Sitzend, Füße leicht angehoben, Kettlebell seitlich hin und her drehen.',
    muscleGroups: ['Core', 'Obliques'],
    difficulty: 'Mittel',
    equipment: 'Kettlebell',
    icon: '🌀',
    tips: 'Füße vom Boden heben für mehr Intensität',
  },
  {
    id: 'hanging-knee-raises',
    name: 'Hanging Knee Raises',
    description: 'An der Klimmzugstange hängen, Knie kontrolliert zur Brust ziehen.',
    muscleGroups: ['Core', 'Hüftbeuger'],
    difficulty: 'Mittel',
    equipment: 'Klimmzugstange',
    icon: '🦵',
    tips: 'Nicht schwingen! Kontrolliert und langsam',
  },
  {
    id: 'hanging-leg-raises',
    name: 'Hanging Leg Raises',
    description: 'An der Klimmzugstange hängen, gestreckte Beine bis auf Hüfthöhe anheben.',
    muscleGroups: ['Core', 'Hüftbeuger'],
    difficulty: 'Fortgeschritten',
    equipment: 'Klimmzugstange',
    icon: '🦿',
    tips: 'Beine gestreckt, kein Schwung nutzen',
  },
  {
    id: 'kb-swings',
    name: 'KB Swings',
    description: 'Explosiver Hüftschwung mit der Kettlebell. Rücken gerade, Kraft aus der Hüfte.',
    muscleGroups: ['Ganzkörper', 'Hüfte', 'Rücken'],
    difficulty: 'Mittel',
    equipment: 'Kettlebell',
    icon: '🔔',
    tips: 'Kraft kommt aus der HÜFTE, nicht aus den Armen',
  },
  {
    id: 'goblet-squats',
    name: 'Goblet Squats',
    description: 'Kettlebell vor der Brust halten, tief in die Kniebeuge gehen. Rücken gerade.',
    muscleGroups: ['Beine', 'Core'],
    difficulty: 'Anfänger',
    equipment: 'Kettlebell',
    icon: '🏋️',
    tips: 'Knie nach außen drücken, tief gehen',
  },
  {
    id: 'plyo-push-ups',
    name: 'Plyo-Liegestütze',
    description: 'Explosive Liegestütze mit Abdrücken vom Boden. Weiche Landung.',
    muscleGroups: ['Brust', 'Trizeps', 'Explosivkraft'],
    difficulty: 'Fortgeschritten',
    icon: '💥',
    tips: 'Weich landen, Handgelenke schonen',
  },
  {
    id: 'split-squats-l',
    name: 'Split Squats links',
    description: 'Ausfallschritt-Position, linkes Bein vorne. Kontrolliert absenken und hochdrücken.',
    muscleGroups: ['Beine', 'Gesäß'],
    difficulty: 'Anfänger',
    icon: '🦵',
    tips: 'Knie bleibt über dem Fuß, nicht nach innen',
  },
  {
    id: 'split-squats-r',
    name: 'Split Squats rechts',
    description: 'Ausfallschritt-Position, rechtes Bein vorne. Kontrolliert absenken und hochdrücken.',
    muscleGroups: ['Beine', 'Gesäß'],
    difficulty: 'Anfänger',
    icon: '🦵',
    tips: 'Knie bleibt über dem Fuß, nicht nach innen',
  },
  {
    id: 'high-knees',
    name: 'High Knees',
    description: 'Auf der Stelle laufen, Knie abwechselnd hoch zur Brust ziehen. Hohe Frequenz.',
    muscleGroups: ['Kardio', 'Beine'],
    difficulty: 'Anfänger',
    icon: '🏃',
    tips: 'Knie auf Hüfthöhe, Arme mitbewegen',
  },
  {
    id: 'pull-ups',
    name: 'Klimmzüge',
    description: 'Breiter Obergriff an der Stange, Körper kontrolliert hochziehen bis Kinn über der Stange.',
    muscleGroups: ['Rücken', 'Bizeps', 'Schultern'],
    difficulty: 'Fortgeschritten',
    equipment: 'Klimmzugstange',
    icon: '🧗',
    tips: 'Schulterblätter zusammenziehen, voller Bewegungsumfang',
  },
  {
    id: 'kb-row-l',
    name: 'KB Row links',
    description: 'Vorgebeugt, linke Hand zieht Kettlebell zum Körper. Schulterblatt zusammenziehen.',
    muscleGroups: ['Rücken', 'Bizeps'],
    difficulty: 'Mittel',
    equipment: 'Kettlebell',
    icon: '🚣',
    tips: 'Oberkörper stabil, nur der Arm bewegt sich',
  },
  {
    id: 'kb-row-r',
    name: 'KB Row rechts',
    description: 'Vorgebeugt, rechte Hand zieht Kettlebell zum Körper. Schulterblatt zusammenziehen.',
    muscleGroups: ['Rücken', 'Bizeps'],
    difficulty: 'Mittel',
    equipment: 'Kettlebell',
    icon: '🚣',
    tips: 'Oberkörper stabil, nur der Arm bewegt sich',
  },
  {
    id: 'chin-ups',
    name: 'Chin-ups',
    description: 'Enger Untergriff an der Stange. Körper hochziehen, Bizeps und Rücken aktivieren.',
    muscleGroups: ['Bizeps', 'Rücken'],
    difficulty: 'Fortgeschritten',
    equipment: 'Klimmzugstange',
    icon: '🧗',
    tips: 'Untergriff (Handflächen zu dir), enger als schulterbreit',
  },
  {
    id: 'kb-clean-press',
    name: 'KB Clean & Press',
    description: 'Kettlebell vom Boden zur Schulter cleanen, dann über Kopf drücken. Wechselseitig.',
    muscleGroups: ['Ganzkörper', 'Schultern'],
    difficulty: 'Fortgeschritten',
    equipment: 'Kettlebell',
    icon: '⬆️',
    tips: 'Flüssige Bewegung, Clean und Press verbinden',
  },
  {
    id: 'kb-snatch',
    name: 'KB Snatch',
    description: 'Explosive Bewegung: Kettlebell in einem Zug vom Boden über den Kopf. Wechselseitig.',
    muscleGroups: ['Ganzkörper', 'Schultern', 'Explosivkraft'],
    difficulty: 'Fortgeschritten',
    equipment: 'Kettlebell',
    icon: '🚀',
    tips: 'Handgelenk beim Lockout drehen, KB fällt nicht auf Arm',
  },
  {
    id: 'mountain-climbers',
    name: 'Mountain Climbers',
    description: 'Liegestütz-Position, Knie abwechselnd schnell zur Brust ziehen.',
    muscleGroups: ['Kardio', 'Core', 'Schultern'],
    difficulty: 'Anfänger',
    icon: '⛰️',
    tips: 'Hüfte tief halten, hohes Tempo',
  },
  {
    id: 'kb-swing-single',
    name: 'KB Swing einarmig',
    description: 'Einarmiger Kettlebell Swing. Mehr Griffkraft und Rotationsstabilität gefordert.',
    muscleGroups: ['Ganzkörper', 'Griffkraft'],
    difficulty: 'Fortgeschritten',
    equipment: 'Kettlebell',
    icon: '💪',
    tips: 'Hüfte gerade halten, nicht rotieren',
  },
  {
    id: 'hollow-body',
    name: 'Hollow Body Hold',
    description: 'Auf dem Rücken liegend, Arme und Beine gestreckt vom Boden heben. Unterer Rücken bleibt am Boden.',
    muscleGroups: ['Core'],
    difficulty: 'Mittel',
    icon: '🍌',
    tips: 'Unterer Rücken muss den Boden berühren!',
  },
  {
    id: 'kb-thrusters',
    name: 'KB Thrusters',
    description: 'Kombination aus Kniebeuge und Overhead Press in einer flüssigen Bewegung.',
    muscleGroups: ['Ganzkörper', 'Beine', 'Schultern'],
    difficulty: 'Fortgeschritten',
    equipment: 'Kettlebell',
    icon: '🏋️',
    tips: 'Schwung aus der Kniebeuge nutzen',
  },
  {
    id: 'kb-woodchops',
    name: 'KB Woodchops',
    description: 'Diagonale Rotationsbewegung mit der Kettlebell von unten nach oben. Wechselseitig.',
    muscleGroups: ['Core', 'Obliques', 'Schultern'],
    difficulty: 'Mittel',
    equipment: 'Kettlebell',
    icon: '🪓',
    tips: 'Kraft kommt aus der Hüftrotation',
  },
  {
    id: 'burpees',
    name: 'Burpees',
    description: 'Ganzkörperübung: hinlegen, aufspringen, Hände über Kopf. Maximales Tempo.',
    muscleGroups: ['Ganzkörper', 'Kardio'],
    difficulty: 'Fortgeschritten',
    icon: '🤸',
    tips: 'Brust berührt den Boden, voller Sprung nach oben',
  },
  {
    id: 'plank',
    name: 'Plank',
    description: 'Unterarmstütz halten. Körper bildet eine gerade Linie. Core maximal anspannen.',
    muscleGroups: ['Core', 'Schultern'],
    difficulty: 'Anfänger',
    icon: '🧘',
    tips: 'Hüfte nicht durchhängen lassen',
  },
  {
    id: 'shadowboxing',
    name: 'Shadowboxing',
    description: 'Freies Boxen in der Luft. Kombinationen aus Jab, Cross, Haken und Ausweichbewegungen.',
    muscleGroups: ['Kardio', 'Schultern', 'Core', 'Technik'],
    difficulty: 'Mittel',
    icon: '🥊',
    tips: 'Beinarbeit nicht vergessen! Bewege dich im Raum',
  },
  {
    id: 'kb-shrugs',
    name: 'KB Shrugs',
    description: 'Kettlebells seitlich halten, Schultern zu den Ohren hochziehen und langsam senken.',
    muscleGroups: ['Nacken', 'Trapez'],
    difficulty: 'Anfänger',
    equipment: 'Kettlebell',
    icon: '🤷',
    tips: '2 Sekunden oben halten, langsam senken',
  },
  {
    id: 'neck-bridges',
    name: 'Neck Bridges',
    description: 'Nackenbrücke halten. Vorsichtig ausführen, Nackenmuskulatur stärken.',
    muscleGroups: ['Nacken'],
    difficulty: 'Fortgeschritten',
    icon: '🌉',
    tips: 'Vorsichtig! Langsam steigern, bei Schmerz aufhören',
  },
  // === STRETCHING / DEHNEN (Kampfkunst-Fokus) ===
  {
    id: 'hip-flexor-stretch',
    name: 'Hüftbeuger-Dehnung',
    description: 'Ausfallschritt, hinteres Knie am Boden. Hüfte nach vorne schieben und halten.',
    muscleGroups: ['Hüfte', 'Beine', 'Dehnung'],
    difficulty: 'Anfänger',
    icon: '🧘',
    tips: 'Aufrechter Oberkörper, Hüfte aktiv nach vorne drücken',
  },
  {
    id: 'hamstring-stretch',
    name: 'Beinrückseite dehnen',
    description: 'Ein Bein gestreckt nach vorne, Oberkörper langsam vorbeugen. Rücken gerade halten.',
    muscleGroups: ['Beine', 'Rücken', 'Dehnung'],
    difficulty: 'Anfänger',
    icon: '🦵',
    tips: 'Nicht wippen! Statisch halten und in die Dehnung atmen',
  },
  {
    id: 'side-split-stretch',
    name: 'Seitlicher Spagat (Grätsche)',
    description: 'Beine seitlich öffnen, Oberkörper nach vorne ablegen. Für hohe Kicks essentiell.',
    muscleGroups: ['Beine', 'Hüfte', 'Dehnung'],
    difficulty: 'Fortgeschritten',
    icon: '🤸',
    tips: 'Knie zeigen nach oben, langsam tiefer gehen über Wochen',
  },
  {
    id: 'front-split-stretch',
    name: 'Frontspagat-Vorbereitung',
    description: 'Ein Bein nach vorne, eins nach hinten strecken. So tief wie möglich, mit Händen abstützen.',
    muscleGroups: ['Beine', 'Hüfte', 'Dehnung'],
    difficulty: 'Fortgeschritten',
    icon: '🤸',
    tips: 'Hüfte gerade halten, beide Hüftknochen nach vorne',
  },
  {
    id: 'shoulder-stretch',
    name: 'Schulterdehnung',
    description: 'Arm quer über die Brust ziehen und mit dem anderen Arm halten.',
    muscleGroups: ['Schultern', 'Dehnung'],
    difficulty: 'Anfänger',
    icon: '💪',
    tips: 'Schulter nicht hochziehen, entspannt halten',
  },
  {
    id: 'chest-opener',
    name: 'Brustöffner',
    description: 'Hände hinter dem Rücken verschränken, Brust rausstrecken, Arme nach oben ziehen.',
    muscleGroups: ['Brust', 'Schultern', 'Dehnung'],
    difficulty: 'Anfänger',
    icon: '🫁',
    tips: 'Schulterblätter zusammenziehen, tief atmen',
  },
  {
    id: 'scorpion-stretch',
    name: 'Skorpion-Stretch',
    description: 'Bauchlage, ein Bein über den Körper zur gegenüberliegenden Seite drehen.',
    muscleGroups: ['Hüfte', 'Rücken', 'Dehnung'],
    difficulty: 'Mittel',
    icon: '🦂',
    tips: 'Langsam und kontrolliert, Schultern bleiben am Boden',
  },
  {
    id: 'pigeon-stretch',
    name: 'Tauben-Stretch',
    description: 'Ein Bein angewinkelt vorne, das andere gestreckt nach hinten. Tiefe Hüftöffnung.',
    muscleGroups: ['Hüfte', 'Gesäß', 'Dehnung'],
    difficulty: 'Mittel',
    icon: '🕊️',
    tips: 'Wichtig für Kicks! Hüfte gerade halten',
  },
  {
    id: 'calf-stretch',
    name: 'Wadendehnung',
    description: 'Ausfallschritt an der Wand, hintere Ferse am Boden drücken.',
    muscleGroups: ['Beine', 'Dehnung'],
    difficulty: 'Anfänger',
    icon: '🦶',
    tips: 'Ferse komplett am Boden, Bein gestreckt',
  },
  {
    id: 'quad-stretch',
    name: 'Oberschenkel-Dehnung',
    description: 'Im Stehen einen Fuß zum Gesäß ziehen. Mit einer Hand festhalten.',
    muscleGroups: ['Beine', 'Dehnung'],
    difficulty: 'Anfänger',
    icon: '🦵',
    tips: 'Knie zeigt nach unten, Hüfte nach vorne schieben',
  },
  {
    id: 'cobra-stretch',
    name: 'Kobra-Stretch',
    description: 'Bauchlage, Oberkörper mit den Armen nach oben drücken. Rücken durchstrecken.',
    muscleGroups: ['Rücken', 'Core', 'Dehnung'],
    difficulty: 'Anfänger',
    icon: '🐍',
    tips: 'Becken bleibt am Boden, langsam hochdrücken',
  },
  {
    id: 'butterfly-stretch',
    name: 'Schmetterling',
    description: 'Sitzend, Fußsohlen zusammen, Knie nach außen drücken. Für Hüftflexibilität.',
    muscleGroups: ['Hüfte', 'Beine', 'Dehnung'],
    difficulty: 'Anfänger',
    icon: '🦋',
    tips: 'Rücken gerade, mit Ellenbogen Knie nach unten drücken',
  },
  {
    id: 'world-greatest-stretch',
    name: 'World\'s Greatest Stretch',
    description: 'Ausfallschritt, Hand zum Boden, andere Hand zur Decke drehen. Die beste Ganzkörper-Dehnung.',
    muscleGroups: ['Ganzkörper', 'Hüfte', 'Rücken', 'Dehnung'],
    difficulty: 'Mittel',
    icon: '🌍',
    tips: 'Rotation aus der Brustwirbelsäule, Blick folgt der Hand',
  },
  {
    id: 'side-kick-stretch',
    name: 'Seitkick-Dehnung',
    description: 'Breiter Stand, Gewicht auf ein Bein verlagern, das andere Bein gestreckt zur Seite dehnen.',
    muscleGroups: ['Beine', 'Hüfte', 'Dehnung'],
    difficulty: 'Mittel',
    icon: '🥋',
    tips: 'Essentiell für Seitkicks! Fußspitze zeigt nach vorne',
  },
  {
    id: 'roundhouse-hip-opener',
    name: 'Roundhouse Hüftöffner',
    description: 'An der Wand abstützen, Knie zur Seite hochziehen und Kreise machen. Öffnet die Hüfte für Roundhouse-Kicks.',
    muscleGroups: ['Hüfte', 'Dehnung'],
    difficulty: 'Mittel',
    icon: '🥊',
    tips: 'Große, langsame Kreise in beide Richtungen',
  },
];

export function getExerciseById(id: string): Exercise | undefined {
  return EXERCISES.find((e) => e.id === id);
}
